### ISSUE TITLE
[BUG] "artists_limit" is being ignored for Album Artists

### ISSUE THREAD

**Issue by cheesetosti** [unspok3n/beatportdl#79]
### Description
When downloading a release with 3+ artists for that album, my `artists_short_form` value is being ignored when tagging the metadata. This value only works for creation of the release folder.

My config:
```
artists_limit: 3
artists_short_form: "Various Artists"
```

And my folder comes out fine ("Various Artists"):
`Various Artists - Sunset Gathering, Vol. 4 (Original Mix) (2025)`

But in the metadata the album's artists aren't short form:
Album Artist : Leo N, Alessa Khin, KOFA, DARNO, Vav Vardanian, Olendo, BEBO (EG), try-ky, Andres Matheus, Sinvergüenza

### Steps To Reproduce

1. Use latest commit
2. Download an album with multiple artists (3+ in my case)
3. Enjoy lol

### OS

arch btw.

### Version

8c566328c011d2b6b72ceae30b7416e996c8474c

**Comment by unspok3n** [comment]
This is intentional, it's mentioned in the readme. But you can use _limited keys for artists and remixers now (`track_artists_limited`, `track_remixers_limited`, `release_artists_limited`, `release_remixers_limited`)

a25243fdf98afde9fa54fe45b663cecb53e813c5

**Comment by unspok3n** [comment]
Are you sure you are using it correctly?

```yaml
tag_mappings:
  flac:
    track_name: "TITLE"
    track_artists_limited: "ARTIST"
    track_number: "TRACKNUMBER"
    track_subgenre_or_genre: "GENRE"
    track_key: "KEY"
    track_bpm: "BPM"
    track_isrc: "ISRC"

    release_name: "ALBUM"
    release_artists_limited: "ALBUMARTIST"
    release_date: "DATE"
    release_track_count: "TOTALTRACKS"
    release_catalog_number: "CATALOGNUMBER"
    release_label: "LABEL"
  m4a:
    track_name: "TITLE"
    track_artists_limited: "ARTIST"
    track_number: "TRACKNUMBER"
    track_genre: "GENRE"
    track_key: "KEY"
    track_bpm: "BPM"
    track_isrc: "ISRC"

    release_name: "ALBUM"
    release_artists_limited: "ALBUMARTIST"
    release_date: "DATE"
    release_track_count: "TOTALTRACKS"
    release_catalog_number: "CATALOGNUMBER"
    release_label: "LABEL"
```
